apiVersion: v1
kind: Service
metadata:
  name: gerrit
spec:
  ports:
  - name: "gerrit"
    port: 8080
    targetPort: 8080
  - name: "gerit-mysql"
    port: 3306
    targetPort: 3306
  - name: "gerrit-server"
    port: 29418
    targetPort: 29418
  selector:
    app: gerrit
  type: ClusterIP
